### ISSUE TITLE
How do I contribute ?

### ISSUE THREAD

**Issue by alexnavis** [jonnystorm/snmp-elixir#1]
Hi Jonny,

Thanks a lot for taking time to do open source your work. I would be happy to contribute to this project. Please let me know what are the areas I can contribute and it would be good to create a github issue so that it can help to have a conversation on the same.

Thanks,
Alex

**Comment by jonnystorm** [comment]
Hi, Alex, and thanks for reaching out to me.

At this point, feel free to work on anything: v3 USM, basic operations, tests--whatever. I've been beating on Cisco ASA-to-FTD migrations since I put up the repo, and I haven't had the energy to revisit one of the large obstacles with this lib: USM engine discovery, which is effectively missing from OTP.

I reckon the low-hanging fruit is `get` and `set`, and this would at least make the lib usable for v1/v2c. For any serious work, though, the big one is `table`, and I suspect implementing that will require more than a few bulkgets and a handful of logic--but I hope I'm wrong. As for `walk`, I never worry much about it.

Other ways you can help include calling me out on impoverished design decisions or overcomplicated code. The current code is basically a signpost--a big spike to serve as documentation to myself and others--and it stands as nascent proof that an SNMP client lib built on OTP, without a mess of configuration files, is possible. Whether or not I've done "the right thing" is another matter.

As far as accepting contributions, I will accept everything. I subscribe to Pieter Hintjens's philosophy when it comes to accepting or denying contributions: any pull that doesn't break tests is a good pull. Of course we would need tests to break, first, and therefore all pulls are currently accepted. :)

**Comment by alexnavis** [comment]
Hi Johnny,

Thanks a lot for the github issues and the very detailed narrative on the tasks. I will go through the current code and start with working one of the low hanging tasks to be comfortable. 

Thanks again.

Thanks,
Alex

**Comment by jonnystorm** [comment]
You're quite welcome. Please let me know if you have any questions.
