### ISSUE TITLE
Make snmp_ex available on Hex as a package

### ISSUE THREAD

**Issue by TomHoenderdos** [jonnystorm/snmp-elixir#39]
Hey @jonnystorm!

I would like to push snmp_ex to Hex (as this is the package manager for Elixir). But by doing so we need netaddr_ex, jds_math_ex, linear_ex also on Hex. 
Would you be up to it to do that?

Please let me know :)

**Comment by jonnystorm** [comment]
Thanks for the issue, Tom. :)

I agree that Hex availability is important for `snmp_ex`, at this stage. And I certainly should have put `netaddr_ex` there long ago. However, my feeling towards the convenience libraries `linear_ex` and `jds_math_ex` is somewhat adversarial. This is because they have no clear purpose of their own; they merely permit me a kind of laziness.

I think I'll go ahead and vendorize the few convenience functions `netaddr_ex` relies on, freeing it once and for all from `jds_math_ex` and `linear_ex`. Then I can push that to Hex and clean up the `snmp_ex` deps, making it as self-contained as it reasonably can be.

I'll let you know once I've got that done. Then you can do me the honor of putting `snmp_ex` on Hex. :D

**Comment by jonnystorm** [comment]
All right. As of c071379, `snmp-ex` only depends on `netaddr_ex` via Hex.

Take it away, @TomHoenderdos!

**Comment by TomHoenderdos** [comment]
Thanks!
